package com.merkle.oss.aem.environmentbadge.services.impl;

import com.merkle.oss.aem.environmentbadge.services.AEMEnvironmentBadgeConfigService;
import org.apache.commons.lang3.StringUtils;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.ConfigurationPolicy;
import org.osgi.service.component.annotations.Modified;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.Designate;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import org.osgi.service.metatype.annotations.Option;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Component implementing the {@link AEMEnvironmentBadgeConfigService}.
 * * <p>This service manages the configuration for the AEM environment badge component,
 * retrieving settings defined via the OSGi Configuration console ({@code sling:OsgiConfig} files).</p>
 */
@Component(
        service = AEMEnvironmentBadgeConfigService.class,
        immediate = true,
        configurationPolicy = ConfigurationPolicy.REQUIRE
)
@Designate(ocd = AEMEnvironmentBadgeConfigServiceImpl.AEMEnvironmentBadgeConfig.class)
public class AEMEnvironmentBadgeConfigServiceImpl implements AEMEnvironmentBadgeConfigService {

    private static final Logger LOG = LoggerFactory.getLogger(AEMEnvironmentBadgeConfigServiceImpl.class);

    private AEMEnvironmentBadgeConfig config;

    /**
     * Activates or modifies the service, retrieving the configuration parameters
     * from the OSGi Configuration.
     *
     * @param config The injected configuration object generated by the Metatype service.
     */
    @Activate
    @Modified
    public void activate(final AEMEnvironmentBadgeConfig config) {
        this.config = config;
        LOG.info("AEM Environment Badge Config - Service activated.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isEnableDocumentTitlePrefix() {
        return config.enableDocumentTitlePrefix() && StringUtils.isNotBlank(getDocumentTitlePrefix());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getDocumentTitlePrefix() {
        return config.documentTitlePrefix();
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isEnableBadge() {
        return config.enableBadge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getBadgeTitle() {
        return config.badgeTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getBadgeBackgroundColor() {
        return config.badgeBackgroundColor();
    }

    /**
     * Defines the OSGi Metatype Configuration for the AEM Environment Badge service.
     * * <p>The properties defined here are used to configure the badge's behavior
     * and appearance in different AEM environments.</p>
     */
    @ObjectClassDefinition(name = "AEM Environment Badge Config")
    public @interface AEMEnvironmentBadgeConfig {

        /**
         * @return Whether to prepend a prefix to the document title (browser tab).
         */
        @AttributeDefinition(name = "Enable document title prefix", description = "Whether to prepend a prefix to the document title (browser tab)")
        boolean enableDocumentTitlePrefix();

        /**
         * @return The string prefix to be prepended to the browser tab title. E.g.: {@code <PREFIX> | <DOCUMENT TITLE>}
         */
        @AttributeDefinition(name = "Document title prefix", description = "The string prefix to be prepended to the document title. E.g.: '<PREFIX> | <DOCUMENT TITLE>'")
        String documentTitlePrefix();

        /**
         * @return Whether the visual badge component and bar component should be rendered in the AEM UI.
         */
        @AttributeDefinition(name = "Enable environment badge", description = "Whether the visual badge component and bar component should be rendered in the AEM UI")
        boolean enableBadge();

        /**
         * @return The text content displayed on the environment badge.
         */
        @AttributeDefinition(name = "Badge title", description = "The text content displayed on the environment badge")
        String badgeTitle();

        /**
         * @return The color string defining the badge's background color. Defaults to "fuchsia".
         */
        @AttributeDefinition(name = "Background color", description = "The color string defining the badge's background color. Defaults to 'fuchsia'",
                options = {
                        @Option(value = "red", label = "red"),
                        @Option(value = "blue", label = "blue"),
                        @Option(value = "green", label = "green"),
                        @Option(value = "orange", label = "orange"),
                        @Option(value = "grey", label = "grey"),
                        @Option(value = "yellow", label = "yellow"),
                        @Option(value = "seafoam", label = "seafoam"),
                        @Option(value = "fuchsia", label = "fuchsia")
                })
        String badgeBackgroundColor() default "fuchsia";

    }

}
